### ISSUE TITLE
cannot flatten arrays of numbers

### ISSUE THREAD

**Issue by noblige** [amirziai/flatten#16] opened 2017-05-04 21:40 UTC
`print flatten_json.unflatten(flatten_json.flatten({'data' : [2]}))` :
`{'data': {'0': 2}}`

**Comment by noblige** [comment] 2017-05-04 21:56
actually, does not have to be numbers:
`print(flatten_json.unflatten(flatten_json.flatten({'data' : ['a']})))`:
`{'data': {'0': 'a'}}`

**Comment by aquilax** [comment] 2017-05-18 10:03
@noblige, `unflatten_list`, handles data with flattened lists

**Comment by EmSyndio** [comment] 2017-06-19 22:02
doesn't seem to work with nested objects:

```
from flatten_json import flatten, unflatten, unflatten_list
a = {"level1":{"level2":[1,2]}}
b = flatten(a,".")
b
{'level1.level2.0': 1, 'level1.level2.1': 2}
c = unflatten(b, ".")
c
{'level1': {'level2': {'1': 2, '0': 1}}}
d = unflatten_list(b,".")
d
{'level1.level2.0': 1, 'level1.level2.1': 2}
```

**Comment by EmSyndio** [comment] 2017-06-19 22:33
seems like the bug is not present in master, but the bug fix is not released.

**Comment by amirziai** [comment] 2017-06-20 06:19
Just released `v0.1.6`. Try `pip install flatten_json --upgrade` and let me know if the issue is fixed.

**Comment by EmSyndio** [comment] 2017-06-20 23:03
Works as expected. thanks a lot for the quick release.

**Comment by amirziai** [comment] 2017-06-20 23:30
Awesome! Closing the issue.

**Closed by amirziai** 2017-06-20 23:30 UTC
